webrtc:
  bitrate:
    min: 2000000
    default: 5000000
    max: 8000000
  gop_length: 30

head_camera:
  enable_zmq: true
  zmq_port: 55555
  enable_webrtc: true
  webrtc_port: 60001
  webrtc_codec: h264
  type: realsense
  image_shape: [480, 640]
  binocular: false
  fps: 30
  video_id: null
  serial_number: null
  physical_path: null

left_wrist_camera:
  enable_zmq: false
  enable_webrtc: false
  type: realsense
  image_shape: [480, 640]
  binocular: false
  fps: 30

right_wrist_camera:
  enable_zmq: false
  enable_webrtc: false
  type: realsense
  image_shape: [480, 640]
  binocular: false
  fps: 30
