"""Shared bilateral motion limits; measured-state visualization is independent."""
import math
import numpy as np

# Live tracking can move aggressively, but staged return/recovery keeps the
# previously validated conservative limits.
TRACKING_PROXIMAL_VELOCITY_LIMIT_DEG_S = 150.0
TRACKING_WRIST_VELOCITY_LIMIT_DEG_S = 180.0
TRACKING_JOINT_ACCELERATION_LIMIT_DEG_S2 = 300.0
POSITION_TRACKING_RATE_S = 12.0
ORIENTATION_TRACKING_RATE_S = 1.5

RETURN_PROXIMAL_VELOCITY_LIMIT_DEG_S = 90.0
RETURN_WRIST_VELOCITY_LIMIT_DEG_S = 180.0
RETURN_JOINT_ACCELERATION_LIMIT_DEG_S2 = 90.0
JOINT_JERK_LIMIT_RAD_S3 = 1.28
RETURN_RIGHT_WAYPOINT_RAD = np.deg2rad(
    [10.0, -35.0, 0.0, 70.0, 0.0, 0.0, 0.0])

TRACKING_ARM_VELOCITY_LIMITS_RAD_S = (
    math.radians(TRACKING_PROXIMAL_VELOCITY_LIMIT_DEG_S),
) * 4 + (
    math.radians(TRACKING_WRIST_VELOCITY_LIMIT_DEG_S),
) * 3
TRACKING_JOINT_VELOCITY_LIMITS_RAD_S = (
    TRACKING_ARM_VELOCITY_LIMITS_RAD_S * 2)
TRACKING_JOINT_VELOCITY_LIMIT_RAD_S = max(
    TRACKING_JOINT_VELOCITY_LIMITS_RAD_S)
TRACKING_JOINT_ACCELERATION_LIMIT_RAD_S2 = math.radians(
    TRACKING_JOINT_ACCELERATION_LIMIT_DEG_S2)

RETURN_ARM_VELOCITY_LIMITS_RAD_S = (
    math.radians(RETURN_PROXIMAL_VELOCITY_LIMIT_DEG_S),
) * 4 + (
    math.radians(RETURN_WRIST_VELOCITY_LIMIT_DEG_S),
) * 3
RETURN_JOINT_VELOCITY_LIMITS_RAD_S = (
    RETURN_ARM_VELOCITY_LIMITS_RAD_S * 2)
RETURN_JOINT_VELOCITY_LIMIT_RAD_S = max(
    RETURN_JOINT_VELOCITY_LIMITS_RAD_S)
RETURN_JOINT_ACCELERATION_LIMIT_RAD_S2 = math.radians(
    RETURN_JOINT_ACCELERATION_LIMIT_DEG_S2)
